In [1]:
import numpy as np

In [2]:
my_list=[10, 20 ,30 ,40 ,50]
my_numpy_array=np.array(my_list)

In [3]:
print(my_numpy_array)

#liste gibi numpy dizisi yapar

[10 20 30 40 50]


In [4]:
type(my_numpy_array)

numpy.ndarray

In [5]:
my_numpy_list=[10,20,30.1,45.65]
my_array=np.array(my_numpy_list)
print(my_array)
type(my_array)



[10.   20.   30.1  45.65]


numpy.ndarray

In [6]:
#parantez içi kadar 0 yazar
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [7]:
#parantez içi kadar 1 yaazar
np.ones(5)


array([1., 1., 1., 1., 1.])

In [8]:
# parantez içi kadar 0-1 arasında rastgele sayı yazar
np.random.random(54)
                 

array([0.06469532, 0.60251492, 0.31213562, 0.34904588, 0.117203  ,
       0.38892377, 0.32995701, 0.50648635, 0.15321764, 0.98534226,
       0.84816285, 0.06839816, 0.74782508, 0.54343695, 0.6844388 ,
       0.11343591, 0.65967543, 0.69698617, 0.28319407, 0.19153859,
       0.71970716, 0.87625235, 0.44744123, 0.98507038, 0.44213576,
       0.42578175, 0.28974619, 0.47084591, 0.5756232 , 0.7269786 ,
       0.46426   , 0.76785047, 0.4974571 , 0.21347339, 0.66394401,
       0.67132817, 0.03597711, 0.2861946 , 0.55286841, 0.82306197,
       0.51252272, 0.44757335, 0.02922227, 0.08338114, 0.91529025,
       0.69083947, 0.1079076 , 0.50427304, 0.20583969, 0.59805251,
       0.90048805, 0.88266135, 0.38239304, 0.41523302])

In [9]:
#iki listeyi toplamaya çalışırsak iki liste yan yana yeni liste olarak yazılır numpyda ise indekslerine göre ilk sayı ilk sayı ile ikinci sayı ikinci 
#sayı ile toplanıp yeni dizi oluşturur
my_list1=[1,2]
my_list2=[2,3]
my_numpy_list1=np.array(my_list1)
my_numpy_list2=np.array(my_list2)
my_numpy_list1+my_numpy_list2

array([3, 5])

In [26]:
#en büyük sayıyı bulur
my_static_array=np.array([10,20,30,40,50])
my_static_array.max()

np.int64(50)

In [27]:
#en küçük sayıyı bulur
my_static_array.min()

np.int64(10)

In [28]:
#tüm sayıları toplar
my_static_array.sum()

np.int64(150)

In [29]:
#tüm sayıları tek tek çarpar

In [30]:
my_static_array*5

array([ 50, 100, 150, 200, 250])

In [31]:

#liste ve uzunluğunu bulma

In [14]:
my_range_list=[0,1,2,3,4,5,6,7]

In [15]:
len(my_range_list)

8

In [16]:
#0dan başlayarak 8 de durarak tek tek sayıları yazar
my_arange=np.arange(0,8)
print(my_arange)

[0 1 2 3 4 5 6 7]


In [17]:
my_arange[0]

np.int64(0)

In [18]:
my_arange[5]

np.int64(5)

In [19]:
my_arange[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
#5 tane rastgele eksili dahil sayı oluşturur
np.random.randn(5)

array([ 1.46093971,  0.89174004,  0.7192195 ,  0.39561278, -2.93397905])

In [21]:
#5 5 satır 10 sütunluk rastgele sayı 

In [22]:
np.random.randn(5,10)

array([[ 0.6850335 , -0.0143151 ,  0.83126089,  0.23520064,  0.38495714,
        -0.29820649,  0.2478258 , -1.6641064 ,  1.86201692,  0.02120363],
       [ 0.2676513 , -1.246641  ,  0.25583709,  0.99473686,  0.46487934,
        -0.36108979,  0.56587689, -1.88250194, -0.83468734,  0.82899991],
       [ 2.65727066,  0.93284625, -0.73996963, -1.24649258, -2.40013129,
         0.53563028, -1.32600484, -0.01833037, -1.22922104,  0.99381983],
       [-0.78612623, -0.60742346, -1.07999561, -0.43632311,  0.25611348,
         0.18025636, -0.26400392, -0.35838992, -1.44112236,  0.39693289],
       [-0.41295854, -0.72165087, -0.45089407, -0.52256452,  0.50387392,
        -1.05563708, -0.77153705, -0.65049395,  1.02850137, -1.4749696 ]])

In [23]:
np.random.randint(5,900,8)

array([450,  32, 632, 567, 189, 295, 184, 880], dtype=int32)

In [24]:
#5 ten başlayıp 900 e kadar 8 rastgele sayı randint olduğu için tam sayı verir🠕

In [25]:
my_array_1=np.array([[1,2],[2,3],[3,4]])
my_random_array=np.random.randint(1,200,2)
print(my_array_1)

[[1 2]
 [2 3]
 [3 4]]
