In [9]:
import numpy as np

In [3]:
my_list=[10, 20 ,30 ,40 ,50]
my_numpy_array=np.array(my_list)

In [50]:
print(my_numpy_array)

#liste gibi numpy dizisi yapar

[10 20 30 40 50]


In [5]:
type(my_numpy_array)

numpy.ndarray

In [9]:
my_numpy_list=[10,20,30.1,45.65]
my_array=np.array(my_numpy_list)
print(my_array)
type(my_array)



[10.   20.   30.1  45.65]


numpy.ndarray

In [18]:
#parantez içi kadar 0 yazar
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [17]:
#parantez içi kadar 1 yaazar
np.ones(5)


array([1., 1., 1., 1., 1.])

In [51]:
# parantez içi kadar 0-1 arasında rastgele sayı yazar
np.random.random(54)
                 

array([0.64153146, 0.31895625, 0.08189882, 0.05942477, 0.21277547,
       0.57178385, 0.29397818, 0.99644894, 0.6348985 , 0.40980859,
       0.46519372, 0.78464081, 0.76291154, 0.58802837, 0.42410794,
       0.82958091, 0.12602963, 0.89859619, 0.92549478, 0.73907677,
       0.60782795, 0.11737209, 0.70572641, 0.94739135, 0.49241789,
       0.94091402, 0.47104344, 0.39548006, 0.30163954, 0.61225632,
       0.44335154, 0.10437236, 0.32577207, 0.62193977, 0.65932632,
       0.84078801, 0.72939914, 0.43618698, 0.76138965, 0.03665462,
       0.4331905 , 0.15979541, 0.52420621, 0.92061995, 0.06316795,
       0.24032046, 0.60533528, 0.4139184 , 0.05233173, 0.84977674,
       0.64056572, 0.304704  , 0.97461006, 0.77284173])

In [23]:
#iki listeyi toplamaya çalışırsak iki liste yan yana yeni liste olarak yazılır numpyda ise indekslerine göre ilk sayı ilk sayı ile ikinci sayı ikinci 
#sayı ile toplanıp yeni dizi oluşturur
my_list1=[1,2]
my_list2=[2,3]
my_numpy_list1=np.array(my_list1)
my_numpy_list2=np.array(my_list2)
my_numpy_list1+my_numpy_list2

array([3, 5])

In [24]:
#en büyük sayıyı bulur
np.array([10,20,30,40,50])
my_static_array.max()

np.int64(50)

In [25]:
#en küçük sayıyı bulur
my_static_array.min()

np.int64(10)

In [11]:
#tüm sayıları toplar
my_static_array.sum()

NameError: name 'my_static_array' is not defined

In [52]:
#tüm sayıları tek tek çarpar

In [31]:
my_static_array*5

array([ 50, 100, 150, 200, 250])

In [ ]:

#liste ve uzunluğunu bulma

In [32]:
my_range_list=[0,1,2,3,4,5,6,7]

In [33]:
len(my_range_list)

8

In [54]:
#0dan başlayarak 8 de durarak tek tek sayıları yazar
my_arange=np.arange(0,8)
print(my_arange)

[0 1 2 3 4 5 6 7]


In [37]:
my_arange[0]

np.int64(0)

In [39]:
my_arange[5]

np.int64(5)

In [40]:
my_arange[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
#5 tane rastgele eksili dahil sayı oluşturur
np.random.randn(5)

array([ 0.45206255, -0.52770117, -0.49868274,  0.92441973, -2.26164456])

In [ ]:
#5 5 satır 10 sütunluk rastgele sayı 

In [46]:
np.random.randn(5,10)

array([[ 0.7311316 ,  0.90421926,  0.26843898,  1.88099579, -0.47690531,
         0.04806124, -0.70543403, -1.06002909,  2.81852165, -1.28595279],
       [ 0.85884175, -0.17565243, -0.28338115, -0.01832188, -0.76853903,
        -1.26597045, -1.45233051, -0.93634689,  1.40322135,  0.58304497],
       [-0.54166544, -1.35595255,  1.15659262, -0.95263121, -2.70638217,
        -0.63861994,  0.14451382, -0.27009345, -0.70346422, -1.67389842],
       [-0.10943044,  0.25102573, -1.0683979 , -0.67610562, -0.14751414,
        -0.07991849, -2.40114325,  0.76021074, -0.20978729, -1.31950387],
       [ 1.47713075,  0.17128847,  1.44449716, -0.13603519,  0.38484474,
        -0.47326561,  0.78702351, -1.3624009 , -1.21719529, -0.5895655 ]])

In [49]:
np.random.randint(5,900,8)

array([ 38,  38, 641, 136, 482, 643, 724, 398], dtype=int32)

In [ ]:
#5 ten başlayıp 900 e kadar 8 rastgele sayı randint olduğu için tam sayı verir🠕

In [10]:
my_array_1=np.array([[1,2],[2,3],[3,4]])
my_random_array=np.random.randint(1,200,2)
print(my_array_1)

[[1 2]
 [2 3]
 [3 4]]
