In [1]:
import numpy as np

In [2]:
my_list=[10, 20 ,30 ,40 ,50]
my_numpy_array=np.array(my_list)

In [3]:
print(my_numpy_array)

#liste gibi numpy dizisi yapar

[10 20 30 40 50]


In [29]:
my_numpy_array_list=[5,10,15,20,25]
my_array_list=np.array(my_numpy_array_list)
my_array_list
type(my_array_list)

numpy.ndarray

In [4]:
type(my_numpy_array)

numpy.ndarray

In [5]:
my_numpy_list=[10,20,30.1,45.65]
my_array=np.array(my_numpy_list)
print(my_array)
type(my_array)



[10.   20.   30.1  45.65]


numpy.ndarray

In [6]:
#parantez içi kadar 0 yazar
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [7]:
#parantez içi kadar 1 yaazar
np.ones(5)


array([1., 1., 1., 1., 1.])

In [8]:
# parantez içi kadar 0-1 arasında rastgele sayı yazar
np.random.random(54)
                 

array([0.1441136 , 0.58246913, 0.89050136, 0.88309914, 0.49390382,
       0.13570361, 0.33161148, 0.31303781, 0.03859837, 0.77589175,
       0.11147418, 0.4894524 , 0.63533683, 0.04371716, 0.55937576,
       0.77784605, 0.05022173, 0.35099129, 0.50000827, 0.34261472,
       0.58229546, 0.43656119, 0.47456847, 0.02016541, 0.24296196,
       0.76937493, 0.46878262, 0.35527385, 0.3144593 , 0.87373407,
       0.00272505, 0.74711014, 0.54942863, 0.45865136, 0.3026215 ,
       0.04089005, 0.55375806, 0.20362891, 0.63238921, 0.31202719,
       0.51605751, 0.95464807, 0.77306137, 0.66224732, 0.58515843,
       0.45911264, 0.47140828, 0.74018254, 0.39849477, 0.82687576,
       0.82835395, 0.96911971, 0.5416647 , 0.59840836])

In [9]:
#iki listeyi toplamaya çalışırsak iki liste yan yana yeni liste olarak yazılır numpyda ise indekslerine göre ilk sayı ilk sayı ile ikinci sayı ikinci 
#sayı ile toplanıp yeni dizi oluşturur
my_list1=[1,2]
my_list2=[2,3]
my_numpy_list1=np.array(my_list1)
my_numpy_list2=np.array(my_list2)
my_numpy_list1+my_numpy_list2

array([3, 5])

In [10]:
#en büyük sayıyı bulur
my_static_array=np.array([10,20,30,40,50])
my_static_array.max()

np.int64(50)

In [11]:
#en küçük sayıyı bulur
my_static_array.min()

np.int64(10)

In [12]:
#tüm sayıları toplar
my_static_array.sum()

np.int64(150)

In [13]:
#tüm sayıları tek tek çarpar

In [14]:
my_static_array*5

array([ 50, 100, 150, 200, 250])

In [15]:

#liste ve uzunluğunu bulma

In [16]:
my_range_list=[0,1,2,3,4,5,6,7]

In [17]:
len(my_range_list)

8

In [18]:
#0dan başlayarak 8 de durarak tek tek sayıları yazar
my_arange=np.arange(0,8)
print(my_arange)

[0 1 2 3 4 5 6 7]


In [19]:
my_arange[0]

np.int64(0)

In [20]:
my_arange[5]

np.int64(5)

In [21]:
my_arange[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
#5 tane rastgele eksili dahil sayı oluşturur
np.random.randn(5)

array([-0.38836614,  0.24049387, -1.25340726, -0.24038922,  0.82066488])

In [23]:
# 10 satır 5 sütunluk rastgele sayı 

In [24]:
np.random.randn(5,10)

array([[-0.62206069,  0.00980555, -0.9499494 ,  0.48730084,  2.10101378,
         0.32034611, -0.32510308, -0.00886667,  0.10429285, -0.39261018],
       [-0.03121204,  1.86624547, -0.3355762 ,  0.13771703, -0.09504896,
        -0.17588684, -1.11859483, -0.13870814,  0.73099705,  0.22651478],
       [ 0.97214608, -1.00940332,  0.62916359, -1.42167087, -0.57255311,
        -1.01889653,  0.82419678,  0.19338892,  0.21919416, -0.74152237],
       [ 1.90964642,  0.11383899, -1.0940589 , -0.21164956, -0.02160126,
        -1.01219915,  0.13128973, -0.29810614,  0.5104188 , -0.09815474],
       [-0.65812492, -0.63817569, -0.79622654, -0.87407525,  1.3504295 ,
        -0.31816813,  1.44444337,  1.30552169,  0.89773212, -1.14234011]])

In [25]:
np.random.randint(5,900,8)

array([678, 491, 571,  27, 234, 132, 601, 393], dtype=int32)

In [26]:
#5 ten başlayıp 900 e kadar 8 rastgele sayı randint olduğu için tam sayı verir🠕

In [31]:
my_array_1=np.array([[1,2],[2,3],[3,4]])
my_random_array=np.random.randint(1,200,2)
my_array_1
my_random_array

array([176,  40], dtype=int32)