In [1]:
import numpy as np

In [2]:
#3 sıra 5 kolon 1
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
# 3 sıra 5 kolon 0
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
# 3 sırsa 5 kolon rasstgele sayılar
np.random.random((3,5))

array([[0.7091533 , 0.31298793, 0.55882129, 0.13177877, 0.25179544],
       [0.48723843, 0.61535515, 0.95240022, 0.44646714, 0.04210212],
       [0.63309169, 0.08906562, 0.07412054, 0.34643084, 0.42962642]])

In [18]:
np.random.random((3,7))

array([[0.1582644 , 0.8165228 , 0.54759337, 0.91707247, 0.31785615,
        0.53613059, 0.10839625],
       [0.94895713, 0.49645082, 0.7824986 , 0.36609603, 0.47576145,
        0.98107613, 0.35999303],
       [0.02187133, 0.49923584, 0.69535237, 0.73591259, 0.32153681,
        0.94931643, 0.96853106]])

In [5]:
#dizileri toplama işlemi 

In [6]:
first_array=np.array([[10,20],[30,40]])
print(first_array)

[[10 20]
 [30 40]]


In [7]:
second_array=np.array([[5,15],[25,35]])


In [8]:
first_array+second_array

array([[15, 35],
       [55, 75]])

In [9]:
only_number=np.array([[1,1]])
first_array+only_number

array([[11, 21],
       [31, 41]])

In [10]:
array_multi= first_array * second_array

In [11]:
print(array_multi)

[[  50  300]
 [ 750 1400]]


In [23]:
dot_array1=np.array([[1,2,3]])
dot_array2=np.array([[2,3],[3,4],[4,5]])
dot_array1.shape
dot_array2.shape
print(dot_array1)

print(dot_array2)

[[1 2 3]]
[[2 3]
 [3 4]
 [4 5]]


In [13]:
#dot_array1 * dot_array2

In [14]:
dot_multi=dot_array1.dot(dot_array2)

In [15]:
print(dot_multi)

[[20 26]]


In [29]:
my_dot_array1=np.array([[5,6,7,8]])
my_dot_array2=np.array([[10,11],[11,12],[12,13],[14,15]])
my_dot_multi=my_dot_array1.dot(my_dot_array2)

In [30]:
my_dot_multi

array([[312, 338]])