In [2]:
import numpy as np


In [3]:
#1-200 ARASI RASTGELE 31 TANE TAM SAYI
new_array=np.random.randint(1,200,31)

In [4]:
print(new_array)

[167  82  37  23 124  89   6  73  29 115 122  71  83 134 103 103  77  20
  55  66 152 152  71  43 187  59   5 144  93 196  48]


In [5]:
#50 DEN BÜYÜK OLANLAR BÖYLE YAZILIRSA TRUE FALSE DÖNER
new_array>50

array([ True,  True, False, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True, False])

In [6]:
#BÖYLE YAZILIRSA 50 DEN BYÜKLER VE KÜÇÜKLER GELİR
new_array[new_array>50]

array([167,  82, 124,  89,  73, 115, 122,  71,  83, 134, 103, 103,  77,
        55,  66, 152, 152,  71, 187,  59, 144,  93, 196], dtype=int32)

In [7]:
new_array[new_array<50]

array([37, 23,  6, 29, 20, 43,  5, 48], dtype=int32)

In [8]:
#transpose & reshape

In [9]:
numpy_array=np.array([[2,3],[3,4],[4,5]])
print(numpy_array)

[[2 3]
 [3 4]
 [4 5]]


In [10]:
# DİZİ SHAPE İ (3,2) OLANI (2,3) YAPAR
numpy_array.transpose()

array([[2, 3, 4],
       [3, 4, 5]])

In [11]:
numpy_array.T

array([[2, 3, 4],
       [3, 4, 5]])

In [12]:
shape_array= np.random.random((3,10))
print(shape_array)

[[0.24904922 0.88237282 0.1990354  0.17024505 0.59648855 0.77171685
  0.43774216 0.05657066 0.18897228 0.39006465]
 [0.51489903 0.45959819 0.33708748 0.25113207 0.53661603 0.74383009
  0.29607438 0.29645277 0.06747529 0.43696189]
 [0.01521447 0.30123496 0.54643709 0.80438326 0.49516665 0.53505359
  0.39300142 0.10540021 0.11707613 0.16177144]]


In [13]:
shape_array.reshape(5,6)

array([[0.24904922, 0.88237282, 0.1990354 , 0.17024505, 0.59648855,
        0.77171685],
       [0.43774216, 0.05657066, 0.18897228, 0.39006465, 0.51489903,
        0.45959819],
       [0.33708748, 0.25113207, 0.53661603, 0.74383009, 0.29607438,
        0.29645277],
       [0.06747529, 0.43696189, 0.01521447, 0.30123496, 0.54643709,
        0.80438326],
       [0.49516665, 0.53505359, 0.39300142, 0.10540021, 0.11707613,
        0.16177144]])