In [2]:
import numpy as np


In [3]:
#1-200 ARASI RASTGELE 31 TANE TAM SAYI
new_array=np.random.randint(1,200,31)

In [4]:
print(new_array)

[113 157 139  12 152 106 177 160  78  37 176  78  65 146  82 108  25 185
 112 111  95  19  33  72  13 198  15 134 151  38 129]


In [5]:
#50 DEN BÜYÜK OLANLAR BÖYLE YAZILIRSA TRUE FALSE DÖNER
new_array>50

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False, False,  True, False,  True, False,
        True,  True, False,  True])

In [6]:
#BÖYLE YAZILIRSA 50 DEN BYÜKLER VE KÜÇÜKLER GELİR
new_array[new_array>50]

array([113, 157, 139, 152, 106, 177, 160,  78, 176,  78,  65, 146,  82,
       108, 185, 112, 111,  95,  72, 198, 134, 151, 129], dtype=int32)

In [7]:
new_array[new_array<50]

array([12, 37, 25, 19, 33, 13, 15, 38], dtype=int32)

In [8]:
#transpose & reshape

In [9]:
numpy_array=np.array([[2,3],[3,4],[4,5]])
print(numpy_array)

[[2 3]
 [3 4]
 [4 5]]


In [10]:
# DİZİ SHAPE İ (3,2) OLANI (2,3) YAPAR
numpy_array.transpose()

array([[2, 3, 4],
       [3, 4, 5]])

In [11]:
numpy_array.T

array([[2, 3, 4],
       [3, 4, 5]])

In [12]:
shape_array= np.random.random((3,10))
print(shape_array)

[[0.39198232 0.23239836 0.64737545 0.02013562 0.66529801 0.12860346
  0.95499048 0.43910913 0.45917142 0.71835125]
 [0.01833844 0.79554421 0.80748751 0.55448169 0.19848548 0.66242582
  0.39053562 0.24107701 0.26725625 0.15629554]
 [0.90172194 0.24582997 0.64243617 0.04599352 0.08676403 0.12940944
  0.28101694 0.2688909  0.68110048 0.05852604]]


In [14]:
shape_array.reshape(5,6)

array([[0.96359548, 0.12587149, 0.11063723, 0.72145682, 0.0455215 ,
        0.66195846],
       [0.13626083, 0.99910654, 0.00156762, 0.9346843 , 0.03363482,
        0.7543315 ],
       [0.8258879 , 0.92980016, 0.40630104, 0.13196756, 0.17651728,
        0.15706576],
       [0.55874438, 0.75072918, 0.13254071, 0.89239196, 0.94854252,
        0.45280098],
       [0.97164199, 0.84198821, 0.66283298, 0.79696402, 0.908797  ,
        0.29755791]])

In [13]:
my_array_1=np.array([[1,2],[2,3],[3,4]])
my_random_array=np.random.randint(1,200,10)
print(my_array_1+my_random_array)

ValueError: operands could not be broadcast together with shapes (3,2) (10,) 