In [1]:
import numpy as np

In [2]:
#3 sıra 5 kolon 1
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
# 3 sıra 5 kolon 0
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
# 3 sırsa 5 kolon rasstgele sayılar
np.random.random((3,5))

array([[0.6546742 , 0.41295127, 0.64542859, 0.98463697, 0.22969611],
       [0.6885071 , 0.03011349, 0.01164078, 0.5819696 , 0.51237258],
       [0.3445807 , 0.69552056, 0.24117259, 0.16063454, 0.0455581 ]])

In [ ]:
#dizileri toplama işlemi 

In [ ]:
first_array=np.array([[10,20],[30,40]])
print(first_array)

In [ ]:
second_array=np.array([[5,15],[25,35]])


In [7]:
first_array+second_array

array([[15, 35],
       [55, 75]])

In [8]:
only_number=np.array([[1,1]])
first_array+only_number

array([[11, 21],
       [31, 41]])

In [10]:
array_multi= first_array * second_array

In [11]:
print(array_multi)

[[  50  300]
 [ 750 1400]]


In [ ]:
dot_array1=np.array([[1,2,3]])
dot_array2=np.array([[2,3],[3,4],[4,5]])
dot_array1.shape
dot_array2.shape
print(dot_array1)
print(dot_array2)

In [21]:
#dot_array1 * dot_array2

In [22]:
dot_multi=dot_array1.dot(dot_array2)

In [23]:
print(dot_multi)

[[20 26]]
