In [3]:
import numpy as np


In [4]:
#1-200 ARASI RASTGELE 31 TANE TAM SAYI
new_array=np.random.randint(1,200,31)

In [5]:
print(new_array)

[162  73 106  67  87   5 159  88  59  55 148 165  74  11   1 189 179  75
 154  31 101 178  63 156  21  91 155 113  14 110  12]


In [6]:
#50 DEN BÜYÜK OLANLAR BÖYLE YAZILIRSA TRUE FALSE DÖNER
new_array>50

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True, False,  True, False])

In [7]:
#BÖYLE YAZILIRSA 50 DEN BYÜKLER VE KÜÇÜKLER GELİR
new_array[new_array>50]

array([162,  73, 106,  67,  87, 159,  88,  59,  55, 148, 165,  74, 189,
       179,  75, 154, 101, 178,  63, 156,  91, 155, 113, 110], dtype=int32)

In [8]:
new_array[new_array<50]

array([ 5, 11,  1, 31, 21, 14, 12], dtype=int32)

In [9]:
#transpose & reshape

In [10]:
numpy_array=np.array([[2,3],[3,4],[4,5]])
print(numpy_array)

[[2 3]
 [3 4]
 [4 5]]


In [11]:
# DİZİ SHAPE İ (3,2) OLANI (2,3) YAPAR
numpy_array.transpose()

array([[2, 3, 4],
       [3, 4, 5]])

In [12]:
numpy_array.T

array([[2, 3, 4],
       [3, 4, 5]])

In [13]:
shape_array= np.random.random((3,10))
print(shape_array)

[[0.96359548 0.12587149 0.11063723 0.72145682 0.0455215  0.66195846
  0.13626083 0.99910654 0.00156762 0.9346843 ]
 [0.03363482 0.7543315  0.8258879  0.92980016 0.40630104 0.13196756
  0.17651728 0.15706576 0.55874438 0.75072918]
 [0.13254071 0.89239196 0.94854252 0.45280098 0.97164199 0.84198821
  0.66283298 0.79696402 0.908797   0.29755791]]


In [14]:
shape_array.reshape(5,6)

array([[0.96359548, 0.12587149, 0.11063723, 0.72145682, 0.0455215 ,
        0.66195846],
       [0.13626083, 0.99910654, 0.00156762, 0.9346843 , 0.03363482,
        0.7543315 ],
       [0.8258879 , 0.92980016, 0.40630104, 0.13196756, 0.17651728,
        0.15706576],
       [0.55874438, 0.75072918, 0.13254071, 0.89239196, 0.94854252,
        0.45280098],
       [0.97164199, 0.84198821, 0.66283298, 0.79696402, 0.908797  ,
        0.29755791]])

In [16]:
my_array_1=np.array([[1,2][2,3],[3,4]])
my_random_array=np.random.randint(1,200,10)
print(my_array_1+my_random_array)

TypeError: list indices must be integers or slices, not tuple